kind: Service
apiVersion: v1
metadata:
  name: jenkins-tools-prd-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    env: development
    app: jenkins-tools